// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LazerTagHostUI {
    
    
    public partial class PlayerSelectionScreen {
        
        private Gtk.HPaned hpaned1;
        
        private Gtk.VBox vboxPlayerControls;
        
        private Gtk.Button buttonDropPlayer;
        
        private Gtk.ComboBoxEntry comboboxentryRenamePlayer;
        
        private Gtk.Button buttonLateJoin;
        
        private Gtk.ToggleButton togglebuttonRelativeScores;
        
        private Gtk.HBox hboxBaseControls;
        
        private Gtk.Button buttonNext;
        
        private Gtk.Button buttonPause;
        
        private Gtk.Button buttonAbortHost;
        
        private Gtk.VBox vbox2;
        
        private Gtk.Label labelTitle;
        
        private LazerTagHostUI.PlayerSelector playerselector;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget LazerTagHostUI.PlayerSelectionScreen
            Stetic.BinContainer.Attach(this);
            this.Name = "LazerTagHostUI.PlayerSelectionScreen";
            // Container child LazerTagHostUI.PlayerSelectionScreen.Gtk.Container+ContainerChild
            this.hpaned1 = new Gtk.HPaned();
            this.hpaned1.CanFocus = true;
            this.hpaned1.Name = "hpaned1";
            this.hpaned1.Position = 267;
            this.hpaned1.BorderWidth = ((uint)(6));
            // Container child hpaned1.Gtk.Paned+PanedChild
            this.vboxPlayerControls = new Gtk.VBox();
            this.vboxPlayerControls.WidthRequest = 150;
            this.vboxPlayerControls.Name = "vboxPlayerControls";
            this.vboxPlayerControls.Spacing = 6;
            // Container child vboxPlayerControls.Gtk.Box+BoxChild
            this.buttonDropPlayer = new Gtk.Button();
            this.buttonDropPlayer.CanFocus = true;
            this.buttonDropPlayer.Name = "buttonDropPlayer";
            this.buttonDropPlayer.UseUnderline = true;
            // Container child buttonDropPlayer.Gtk.Container+ContainerChild
            Gtk.Alignment w1 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w2 = new Gtk.HBox();
            w2.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w3 = new Gtk.Image();
            w3.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-delete", Gtk.IconSize.Menu, 16);
            w2.Add(w3);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w5 = new Gtk.Label();
            w5.LabelProp = Mono.Unix.Catalog.GetString("Drop Player");
            w5.UseUnderline = true;
            w2.Add(w5);
            w1.Add(w2);
            this.buttonDropPlayer.Add(w1);
            this.vboxPlayerControls.Add(this.buttonDropPlayer);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.vboxPlayerControls[this.buttonDropPlayer]));
            w9.Position = 0;
            w9.Expand = false;
            w9.Fill = false;
            // Container child vboxPlayerControls.Gtk.Box+BoxChild
            this.comboboxentryRenamePlayer = Gtk.ComboBoxEntry.NewText();
            this.comboboxentryRenamePlayer.Name = "comboboxentryRenamePlayer";
            this.vboxPlayerControls.Add(this.comboboxentryRenamePlayer);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.vboxPlayerControls[this.comboboxentryRenamePlayer]));
            w10.Position = 1;
            w10.Expand = false;
            w10.Fill = false;
            // Container child vboxPlayerControls.Gtk.Box+BoxChild
            this.buttonLateJoin = new Gtk.Button();
            this.buttonLateJoin.CanFocus = true;
            this.buttonLateJoin.Name = "buttonLateJoin";
            this.buttonLateJoin.UseUnderline = true;
            // Container child buttonLateJoin.Gtk.Container+ContainerChild
            Gtk.Alignment w11 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w12 = new Gtk.HBox();
            w12.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w13 = new Gtk.Image();
            w13.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-add", Gtk.IconSize.Menu, 16);
            w12.Add(w13);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w15 = new Gtk.Label();
            w15.LabelProp = Mono.Unix.Catalog.GetString("Late Join");
            w15.UseUnderline = true;
            w12.Add(w15);
            w11.Add(w12);
            this.buttonLateJoin.Add(w11);
            this.vboxPlayerControls.Add(this.buttonLateJoin);
            Gtk.Box.BoxChild w19 = ((Gtk.Box.BoxChild)(this.vboxPlayerControls[this.buttonLateJoin]));
            w19.Position = 2;
            w19.Expand = false;
            w19.Fill = false;
            // Container child vboxPlayerControls.Gtk.Box+BoxChild
            this.togglebuttonRelativeScores = new Gtk.ToggleButton();
            this.togglebuttonRelativeScores.CanFocus = true;
            this.togglebuttonRelativeScores.Name = "togglebuttonRelativeScores";
            this.togglebuttonRelativeScores.UseUnderline = true;
            // Container child togglebuttonRelativeScores.Gtk.Container+ContainerChild
            Gtk.Alignment w20 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w21 = new Gtk.HBox();
            w21.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w22 = new Gtk.Image();
            w22.Pixbuf = Stetic.IconLoader.LoadIcon(this, "stock_calendar-view-month", Gtk.IconSize.Menu, 16);
            w21.Add(w22);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w24 = new Gtk.Label();
            w24.LabelProp = Mono.Unix.Catalog.GetString("Show Relative Scores");
            w24.UseUnderline = true;
            w21.Add(w24);
            w20.Add(w21);
            this.togglebuttonRelativeScores.Add(w20);
            this.vboxPlayerControls.Add(this.togglebuttonRelativeScores);
            Gtk.Box.BoxChild w28 = ((Gtk.Box.BoxChild)(this.vboxPlayerControls[this.togglebuttonRelativeScores]));
            w28.Position = 3;
            w28.Expand = false;
            w28.Fill = false;
            // Container child vboxPlayerControls.Gtk.Box+BoxChild
            this.hboxBaseControls = new Gtk.HBox();
            this.hboxBaseControls.Name = "hboxBaseControls";
            this.hboxBaseControls.Spacing = 6;
            // Container child hboxBaseControls.Gtk.Box+BoxChild
            this.buttonNext = new Gtk.Button();
            this.buttonNext.CanFocus = true;
            this.buttonNext.Name = "buttonNext";
            this.buttonNext.UseUnderline = true;
            // Container child buttonNext.Gtk.Container+ContainerChild
            Gtk.Alignment w29 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w30 = new Gtk.HBox();
            w30.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w31 = new Gtk.Image();
            w31.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-apply", Gtk.IconSize.Menu, 16);
            w30.Add(w31);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w33 = new Gtk.Label();
            w33.LabelProp = Mono.Unix.Catalog.GetString("Next");
            w33.UseUnderline = true;
            w30.Add(w33);
            w29.Add(w30);
            this.buttonNext.Add(w29);
            this.hboxBaseControls.Add(this.buttonNext);
            Gtk.Box.BoxChild w37 = ((Gtk.Box.BoxChild)(this.hboxBaseControls[this.buttonNext]));
            w37.PackType = ((Gtk.PackType)(1));
            w37.Position = 2;
            w37.Expand = false;
            w37.Fill = false;
            // Container child hboxBaseControls.Gtk.Box+BoxChild
            this.buttonPause = new Gtk.Button();
            this.buttonPause.CanFocus = true;
            this.buttonPause.Name = "buttonPause";
            this.buttonPause.UseUnderline = true;
            // Container child buttonPause.Gtk.Container+ContainerChild
            Gtk.Alignment w38 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w39 = new Gtk.HBox();
            w39.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w40 = new Gtk.Image();
            w40.Pixbuf = Stetic.IconLoader.LoadIcon(this, "stock_appointment-reminder", Gtk.IconSize.Menu, 16);
            w39.Add(w40);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w42 = new Gtk.Label();
            w42.LabelProp = Mono.Unix.Catalog.GetString("Pause");
            w42.UseUnderline = true;
            w39.Add(w42);
            w38.Add(w39);
            this.buttonPause.Add(w38);
            this.hboxBaseControls.Add(this.buttonPause);
            Gtk.Box.BoxChild w46 = ((Gtk.Box.BoxChild)(this.hboxBaseControls[this.buttonPause]));
            w46.PackType = ((Gtk.PackType)(1));
            w46.Position = 3;
            w46.Expand = false;
            w46.Fill = false;
            // Container child hboxBaseControls.Gtk.Box+BoxChild
            this.buttonAbortHost = new Gtk.Button();
            this.buttonAbortHost.CanFocus = true;
            this.buttonAbortHost.Name = "buttonAbortHost";
            this.buttonAbortHost.UseUnderline = true;
            // Container child buttonAbortHost.Gtk.Container+ContainerChild
            Gtk.Alignment w47 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w48 = new Gtk.HBox();
            w48.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w49 = new Gtk.Image();
            w49.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-cancel", Gtk.IconSize.Menu, 16);
            w48.Add(w49);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w51 = new Gtk.Label();
            w51.LabelProp = Mono.Unix.Catalog.GetString("Abort Host");
            w51.UseUnderline = true;
            w48.Add(w51);
            w47.Add(w48);
            this.buttonAbortHost.Add(w47);
            this.hboxBaseControls.Add(this.buttonAbortHost);
            Gtk.Box.BoxChild w55 = ((Gtk.Box.BoxChild)(this.hboxBaseControls[this.buttonAbortHost]));
            w55.PackType = ((Gtk.PackType)(1));
            w55.Position = 4;
            w55.Expand = false;
            w55.Fill = false;
            this.vboxPlayerControls.Add(this.hboxBaseControls);
            Gtk.Box.BoxChild w56 = ((Gtk.Box.BoxChild)(this.vboxPlayerControls[this.hboxBaseControls]));
            w56.PackType = ((Gtk.PackType)(1));
            w56.Position = 5;
            w56.Expand = false;
            w56.Fill = false;
            this.hpaned1.Add(this.vboxPlayerControls);
            Gtk.Paned.PanedChild w57 = ((Gtk.Paned.PanedChild)(this.hpaned1[this.vboxPlayerControls]));
            w57.Resize = false;
            w57.Shrink = false;
            // Container child hpaned1.Gtk.Paned+PanedChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.labelTitle = new Gtk.Label();
            this.labelTitle.Name = "labelTitle";
            this.labelTitle.LabelProp = Mono.Unix.Catalog.GetString("Step Description Here");
            this.vbox2.Add(this.labelTitle);
            Gtk.Box.BoxChild w58 = ((Gtk.Box.BoxChild)(this.vbox2[this.labelTitle]));
            w58.Position = 0;
            w58.Expand = false;
            w58.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.playerselector = new LazerTagHostUI.PlayerSelector();
            this.playerselector.Events = ((Gdk.EventMask)(256));
            this.playerselector.Name = "playerselector";
            this.vbox2.Add(this.playerselector);
            Gtk.Box.BoxChild w59 = ((Gtk.Box.BoxChild)(this.vbox2[this.playerselector]));
            w59.Position = 1;
            this.hpaned1.Add(this.vbox2);
            this.Add(this.hpaned1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
            this.togglebuttonRelativeScores.Toggled += new System.EventHandler(this.RelativeScoresToggled);
        }
    }
}
