
// This file has been generated by the GUI designer. Do not modify.
namespace LazerTagHostUI
{
	public partial class PlayerSelector
	{
		private global::Gtk.Table tablePlayerSelector;

		private global::Gtk.Label labelColumn1;

		private global::Gtk.Label labelColumn2;

		private global::Gtk.Label labelColumn3;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LazerTagHostUI.PlayerSelector
			global::Stetic.BinContainer.Attach (this);
			this.Name = "LazerTagHostUI.PlayerSelector";
			// Container child LazerTagHostUI.PlayerSelector.Gtk.Container+ContainerChild
			this.tablePlayerSelector = new global::Gtk.Table (((uint)(9)), ((uint)(3)), true);
			this.tablePlayerSelector.WidthRequest = 600;
			this.tablePlayerSelector.HeightRequest = 600;
			this.tablePlayerSelector.Name = "tablePlayerSelector";
			this.tablePlayerSelector.RowSpacing = ((uint)(6));
			this.tablePlayerSelector.ColumnSpacing = ((uint)(6));
			this.tablePlayerSelector.BorderWidth = ((uint)(6));
			// Container child tablePlayerSelector.Gtk.Table+TableChild
			this.labelColumn1 = new global::Gtk.Label ();
			this.labelColumn1.Name = "labelColumn1";
			this.labelColumn1.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.tablePlayerSelector.Add (this.labelColumn1);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.tablePlayerSelector[this.labelColumn1]));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tablePlayerSelector.Gtk.Table+TableChild
			this.labelColumn2 = new global::Gtk.Label ();
			this.labelColumn2.Name = "labelColumn2";
			this.labelColumn2.LabelProp = global::Mono.Unix.Catalog.GetString ("label2");
			this.tablePlayerSelector.Add (this.labelColumn2);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.tablePlayerSelector[this.labelColumn2]));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tablePlayerSelector.Gtk.Table+TableChild
			this.labelColumn3 = new global::Gtk.Label ();
			this.labelColumn3.Name = "labelColumn3";
			this.labelColumn3.LabelProp = global::Mono.Unix.Catalog.GetString ("label3");
			this.tablePlayerSelector.Add (this.labelColumn3);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.tablePlayerSelector[this.labelColumn3]));
			w3.LeftAttach = ((uint)(2));
			w3.RightAttach = ((uint)(3));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.tablePlayerSelector);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
