// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LazerTagHostUI {
    
    
    public partial class HostWindow {
        
        private LazerTagHostUI.PlayerSelectionScreen playerselectionscreenMain;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget LazerTagHostUI.HostWindow
            this.Name = "LazerTagHostUI.HostWindow";
            this.Title = Mono.Unix.Catalog.GetString("HostWindow");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Container child LazerTagHostUI.HostWindow.Gtk.Container+ContainerChild
            this.playerselectionscreenMain = new LazerTagHostUI.PlayerSelectionScreen();
            this.playerselectionscreenMain.Events = ((Gdk.EventMask)(256));
            this.playerselectionscreenMain.Name = "playerselectionscreenMain";
            this.Add(this.playerselectionscreenMain);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 780;
            this.DefaultHeight = 697;
            this.Show();
        }
    }
}
