
// This file has been generated by the GUI designer. Do not modify.
namespace LazerTagHostUI
{
	public partial class HostWindow
	{
		private global::LazerTagHostUI.PlayerSelectionScreen playerselectionscreenMain;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LazerTagHostUI.HostWindow
			this.Name = "LazerTagHostUI.HostWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("HostWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child LazerTagHostUI.HostWindow.Gtk.Container+ContainerChild
			this.playerselectionscreenMain = new global::LazerTagHostUI.PlayerSelectionScreen ();
			this.playerselectionscreenMain.Events = ((global::Gdk.EventMask)(256));
			this.playerselectionscreenMain.Name = "playerselectionscreenMain";
			this.Add (this.playerselectionscreenMain);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 780;
			this.DefaultHeight = 697;
			this.Show ();
		}
	}
}
