// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.Notebook notebookMain;
    
    private Gtk.Fixed fixed5;
    
    private Gtk.Table table1;
    
    private Gtk.Button buttonStartHost;
    
    private Gtk.CheckButton checkbuttonFriendlyFire;
    
    private Gtk.CheckButton checkbuttonMedicMode;
    
    private Gtk.ComboBox comboboxGameType;
    
    private Gtk.HBox hbox3;
    
    private Gtk.ComboBoxEntry comboboxentryArduinoPorts;
    
    private Gtk.Image imageTransceiverStatus;
    
    private Gtk.Label label11;
    
    private Gtk.Label label12;
    
    private Gtk.Label label14;
    
    private Gtk.Label labelGameTime;
    
    private Gtk.Label labelGameType;
    
    private Gtk.Label labelMega;
    
    private Gtk.Label labelSheild;
    
    private Gtk.Label labelTags;
    
    private Gtk.Label labelTransceiver;
    
    private Gtk.SpinButton spinbuttonGameTime;
    
    private Gtk.SpinButton spinbuttonMega;
    
    private Gtk.SpinButton spinbuttonNumberOfTeams;
    
    private Gtk.SpinButton spinbuttonSheild;
    
    private Gtk.SpinButton spinbuttonTags;
    
    private Gtk.Label labelSetup;
    
    private Gtk.Fixed fixed7;
    
    private Gtk.Table table2;
    
    private Gtk.Button buttonDrop;
    
    private Gtk.Button buttonLateJoin;
    
    private Gtk.HBox hbox2;
    
    private Gtk.ComboBoxEntry comboboxentryName;
    
    private Gtk.Button buttonRename;
    
    private Gtk.Label label19;
    
    private Gtk.Label label20;
    
    private Gtk.Label label21;
    
    private Gtk.Label labelCountdown;
    
    private Gtk.HBox hbox1;
    
    private Gtk.Button buttonCancel;
    
    private Gtk.Button buttonWait;
    
    private Gtk.Button buttonStartGame;
    
    private Gtk.Label labelJoin;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("Lazer Tag Host");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.notebookMain = new Gtk.Notebook();
        this.notebookMain.CanFocus = true;
        this.notebookMain.Name = "notebookMain";
        this.notebookMain.CurrentPage = 1;
        // Container child notebookMain.Gtk.Notebook+NotebookChild
        this.fixed5 = new Gtk.Fixed();
        this.fixed5.Name = "fixed5";
        this.fixed5.HasWindow = false;
        // Container child fixed5.Gtk.Fixed+FixedChild
        this.table1 = new Gtk.Table(((uint)(10)), ((uint)(2)), true);
        this.table1.Name = "table1";
        this.table1.RowSpacing = ((uint)(6));
        this.table1.ColumnSpacing = ((uint)(20));
        // Container child table1.Gtk.Table+TableChild
        this.buttonStartHost = new Gtk.Button();
        this.buttonStartHost.Sensitive = false;
        this.buttonStartHost.CanFocus = true;
        this.buttonStartHost.Name = "buttonStartHost";
        this.buttonStartHost.UseUnderline = true;
        this.buttonStartHost.Label = Mono.Unix.Catalog.GetString("Start");
        this.table1.Add(this.buttonStartHost);
        Gtk.Table.TableChild w1 = ((Gtk.Table.TableChild)(this.table1[this.buttonStartHost]));
        w1.TopAttach = ((uint)(9));
        w1.BottomAttach = ((uint)(10));
        w1.LeftAttach = ((uint)(1));
        w1.RightAttach = ((uint)(2));
        w1.XOptions = ((Gtk.AttachOptions)(4));
        w1.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.checkbuttonFriendlyFire = new Gtk.CheckButton();
        this.checkbuttonFriendlyFire.CanFocus = true;
        this.checkbuttonFriendlyFire.Name = "checkbuttonFriendlyFire";
        this.checkbuttonFriendlyFire.Label = "";
        this.checkbuttonFriendlyFire.DrawIndicator = true;
        this.checkbuttonFriendlyFire.UseUnderline = true;
        this.table1.Add(this.checkbuttonFriendlyFire);
        Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table1[this.checkbuttonFriendlyFire]));
        w2.TopAttach = ((uint)(6));
        w2.BottomAttach = ((uint)(7));
        w2.LeftAttach = ((uint)(1));
        w2.RightAttach = ((uint)(2));
        w2.XOptions = ((Gtk.AttachOptions)(4));
        w2.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.checkbuttonMedicMode = new Gtk.CheckButton();
        this.checkbuttonMedicMode.CanFocus = true;
        this.checkbuttonMedicMode.Name = "checkbuttonMedicMode";
        this.checkbuttonMedicMode.Label = "";
        this.checkbuttonMedicMode.DrawIndicator = true;
        this.checkbuttonMedicMode.UseUnderline = true;
        this.table1.Add(this.checkbuttonMedicMode);
        Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table1[this.checkbuttonMedicMode]));
        w3.TopAttach = ((uint)(7));
        w3.BottomAttach = ((uint)(8));
        w3.LeftAttach = ((uint)(1));
        w3.RightAttach = ((uint)(2));
        w3.XOptions = ((Gtk.AttachOptions)(4));
        w3.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.comboboxGameType = Gtk.ComboBox.NewText();
        this.comboboxGameType.AppendText(Mono.Unix.Catalog.GetString("Custom Laser Tag"));
        this.comboboxGameType.AppendText(Mono.Unix.Catalog.GetString("2-Team Customized Lazer Tag"));
        this.comboboxGameType.AppendText(Mono.Unix.Catalog.GetString("3-Team Customized Lazer Tag"));
        this.comboboxGameType.AppendText(Mono.Unix.Catalog.GetString("Hide And Seek"));
        this.comboboxGameType.AppendText(Mono.Unix.Catalog.GetString("Hunt The Prey"));
        this.comboboxGameType.AppendText(Mono.Unix.Catalog.GetString("2-Kings"));
        this.comboboxGameType.AppendText(Mono.Unix.Catalog.GetString("3-Kings"));
        this.comboboxGameType.AppendText(Mono.Unix.Catalog.GetString("Own The Zone"));
        this.comboboxGameType.Name = "comboboxGameType";
        this.comboboxGameType.Active = 1;
        this.table1.Add(this.comboboxGameType);
        Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table1[this.comboboxGameType]));
        w4.TopAttach = ((uint)(1));
        w4.BottomAttach = ((uint)(2));
        w4.LeftAttach = ((uint)(1));
        w4.RightAttach = ((uint)(2));
        w4.XOptions = ((Gtk.AttachOptions)(4));
        w4.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.hbox3 = new Gtk.HBox();
        this.hbox3.Name = "hbox3";
        this.hbox3.Spacing = 6;
        // Container child hbox3.Gtk.Box+BoxChild
        this.comboboxentryArduinoPorts = Gtk.ComboBoxEntry.NewText();
        this.comboboxentryArduinoPorts.Name = "comboboxentryArduinoPorts";
        this.hbox3.Add(this.comboboxentryArduinoPorts);
        Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox3[this.comboboxentryArduinoPorts]));
        w5.Position = 0;
        w5.Expand = false;
        w5.Fill = false;
        // Container child hbox3.Gtk.Box+BoxChild
        this.imageTransceiverStatus = new Gtk.Image();
        this.imageTransceiverStatus.Name = "imageTransceiverStatus";
        this.imageTransceiverStatus.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-dialog-error", Gtk.IconSize.Menu, 16);
        this.hbox3.Add(this.imageTransceiverStatus);
        Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.hbox3[this.imageTransceiverStatus]));
        w6.Position = 1;
        w6.Expand = false;
        w6.Fill = false;
        this.table1.Add(this.hbox3);
        Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.table1[this.hbox3]));
        w7.LeftAttach = ((uint)(1));
        w7.RightAttach = ((uint)(2));
        w7.XOptions = ((Gtk.AttachOptions)(4));
        w7.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.label11 = new Gtk.Label();
        this.label11.Name = "label11";
        this.label11.LabelProp = Mono.Unix.Catalog.GetString("Friendly Fire");
        this.table1.Add(this.label11);
        Gtk.Table.TableChild w8 = ((Gtk.Table.TableChild)(this.table1[this.label11]));
        w8.TopAttach = ((uint)(6));
        w8.BottomAttach = ((uint)(7));
        w8.XOptions = ((Gtk.AttachOptions)(4));
        w8.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.label12 = new Gtk.Label();
        this.label12.Name = "label12";
        this.label12.LabelProp = Mono.Unix.Catalog.GetString("Medic Mode");
        this.table1.Add(this.label12);
        Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.table1[this.label12]));
        w9.TopAttach = ((uint)(7));
        w9.BottomAttach = ((uint)(8));
        w9.XOptions = ((Gtk.AttachOptions)(4));
        w9.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.label14 = new Gtk.Label();
        this.label14.Name = "label14";
        this.label14.LabelProp = Mono.Unix.Catalog.GetString("Number Of Teams");
        this.table1.Add(this.label14);
        Gtk.Table.TableChild w10 = ((Gtk.Table.TableChild)(this.table1[this.label14]));
        w10.TopAttach = ((uint)(8));
        w10.BottomAttach = ((uint)(9));
        w10.XOptions = ((Gtk.AttachOptions)(4));
        w10.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.labelGameTime = new Gtk.Label();
        this.labelGameTime.Name = "labelGameTime";
        this.labelGameTime.LabelProp = Mono.Unix.Catalog.GetString("Game Time");
        this.table1.Add(this.labelGameTime);
        Gtk.Table.TableChild w11 = ((Gtk.Table.TableChild)(this.table1[this.labelGameTime]));
        w11.TopAttach = ((uint)(2));
        w11.BottomAttach = ((uint)(3));
        w11.XOptions = ((Gtk.AttachOptions)(4));
        w11.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.labelGameType = new Gtk.Label();
        this.labelGameType.Name = "labelGameType";
        this.labelGameType.LabelProp = Mono.Unix.Catalog.GetString("Game Type");
        this.table1.Add(this.labelGameType);
        Gtk.Table.TableChild w12 = ((Gtk.Table.TableChild)(this.table1[this.labelGameType]));
        w12.TopAttach = ((uint)(1));
        w12.BottomAttach = ((uint)(2));
        w12.XOptions = ((Gtk.AttachOptions)(4));
        w12.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.labelMega = new Gtk.Label();
        this.labelMega.Name = "labelMega";
        this.labelMega.LabelProp = Mono.Unix.Catalog.GetString("Mega");
        this.table1.Add(this.labelMega);
        Gtk.Table.TableChild w13 = ((Gtk.Table.TableChild)(this.table1[this.labelMega]));
        w13.TopAttach = ((uint)(5));
        w13.BottomAttach = ((uint)(6));
        w13.XOptions = ((Gtk.AttachOptions)(4));
        w13.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.labelSheild = new Gtk.Label();
        this.labelSheild.Name = "labelSheild";
        this.labelSheild.LabelProp = Mono.Unix.Catalog.GetString("Sheild");
        this.table1.Add(this.labelSheild);
        Gtk.Table.TableChild w14 = ((Gtk.Table.TableChild)(this.table1[this.labelSheild]));
        w14.TopAttach = ((uint)(4));
        w14.BottomAttach = ((uint)(5));
        w14.XOptions = ((Gtk.AttachOptions)(4));
        w14.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.labelTags = new Gtk.Label();
        this.labelTags.Name = "labelTags";
        this.labelTags.LabelProp = Mono.Unix.Catalog.GetString("Tags");
        this.table1.Add(this.labelTags);
        Gtk.Table.TableChild w15 = ((Gtk.Table.TableChild)(this.table1[this.labelTags]));
        w15.TopAttach = ((uint)(3));
        w15.BottomAttach = ((uint)(4));
        w15.XOptions = ((Gtk.AttachOptions)(4));
        w15.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.labelTransceiver = new Gtk.Label();
        this.labelTransceiver.Name = "labelTransceiver";
        this.labelTransceiver.LabelProp = Mono.Unix.Catalog.GetString("Transceiver");
        this.table1.Add(this.labelTransceiver);
        Gtk.Table.TableChild w16 = ((Gtk.Table.TableChild)(this.table1[this.labelTransceiver]));
        w16.XOptions = ((Gtk.AttachOptions)(4));
        w16.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.spinbuttonGameTime = new Gtk.SpinButton(0, 99, 1);
        this.spinbuttonGameTime.CanFocus = true;
        this.spinbuttonGameTime.Name = "spinbuttonGameTime";
        this.spinbuttonGameTime.Adjustment.PageIncrement = 10;
        this.spinbuttonGameTime.ClimbRate = 1;
        this.spinbuttonGameTime.Numeric = true;
        this.spinbuttonGameTime.Value = 10;
        this.table1.Add(this.spinbuttonGameTime);
        Gtk.Table.TableChild w17 = ((Gtk.Table.TableChild)(this.table1[this.spinbuttonGameTime]));
        w17.TopAttach = ((uint)(2));
        w17.BottomAttach = ((uint)(3));
        w17.LeftAttach = ((uint)(1));
        w17.RightAttach = ((uint)(2));
        w17.XOptions = ((Gtk.AttachOptions)(4));
        w17.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.spinbuttonMega = new Gtk.SpinButton(0, 100, 1);
        this.spinbuttonMega.CanFocus = true;
        this.spinbuttonMega.Name = "spinbuttonMega";
        this.spinbuttonMega.Adjustment.PageIncrement = 10;
        this.spinbuttonMega.ClimbRate = 1;
        this.spinbuttonMega.Numeric = true;
        this.spinbuttonMega.Value = 10;
        this.table1.Add(this.spinbuttonMega);
        Gtk.Table.TableChild w18 = ((Gtk.Table.TableChild)(this.table1[this.spinbuttonMega]));
        w18.TopAttach = ((uint)(5));
        w18.BottomAttach = ((uint)(6));
        w18.LeftAttach = ((uint)(1));
        w18.RightAttach = ((uint)(2));
        w18.XOptions = ((Gtk.AttachOptions)(4));
        w18.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.spinbuttonNumberOfTeams = new Gtk.SpinButton(1, 3, 1);
        this.spinbuttonNumberOfTeams.CanFocus = true;
        this.spinbuttonNumberOfTeams.Name = "spinbuttonNumberOfTeams";
        this.spinbuttonNumberOfTeams.Adjustment.PageIncrement = 10;
        this.spinbuttonNumberOfTeams.ClimbRate = 1;
        this.spinbuttonNumberOfTeams.Numeric = true;
        this.spinbuttonNumberOfTeams.Value = 1;
        this.table1.Add(this.spinbuttonNumberOfTeams);
        Gtk.Table.TableChild w19 = ((Gtk.Table.TableChild)(this.table1[this.spinbuttonNumberOfTeams]));
        w19.TopAttach = ((uint)(8));
        w19.BottomAttach = ((uint)(9));
        w19.LeftAttach = ((uint)(1));
        w19.RightAttach = ((uint)(2));
        w19.XOptions = ((Gtk.AttachOptions)(4));
        w19.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.spinbuttonSheild = new Gtk.SpinButton(0, 99, 1);
        this.spinbuttonSheild.CanFocus = true;
        this.spinbuttonSheild.Name = "spinbuttonSheild";
        this.spinbuttonSheild.Adjustment.PageIncrement = 10;
        this.spinbuttonSheild.ClimbRate = 1;
        this.spinbuttonSheild.Numeric = true;
        this.spinbuttonSheild.Value = 30;
        this.table1.Add(this.spinbuttonSheild);
        Gtk.Table.TableChild w20 = ((Gtk.Table.TableChild)(this.table1[this.spinbuttonSheild]));
        w20.TopAttach = ((uint)(4));
        w20.BottomAttach = ((uint)(5));
        w20.LeftAttach = ((uint)(1));
        w20.RightAttach = ((uint)(2));
        w20.XOptions = ((Gtk.AttachOptions)(4));
        w20.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.spinbuttonTags = new Gtk.SpinButton(0, 99, 1);
        this.spinbuttonTags.CanFocus = true;
        this.spinbuttonTags.Name = "spinbuttonTags";
        this.spinbuttonTags.Adjustment.PageIncrement = 10;
        this.spinbuttonTags.ClimbRate = 1;
        this.spinbuttonTags.Numeric = true;
        this.spinbuttonTags.Value = 10;
        this.table1.Add(this.spinbuttonTags);
        Gtk.Table.TableChild w21 = ((Gtk.Table.TableChild)(this.table1[this.spinbuttonTags]));
        w21.TopAttach = ((uint)(3));
        w21.BottomAttach = ((uint)(4));
        w21.LeftAttach = ((uint)(1));
        w21.RightAttach = ((uint)(2));
        w21.XOptions = ((Gtk.AttachOptions)(4));
        w21.YOptions = ((Gtk.AttachOptions)(4));
        this.fixed5.Add(this.table1);
        Gtk.Fixed.FixedChild w22 = ((Gtk.Fixed.FixedChild)(this.fixed5[this.table1]));
        w22.X = 6;
        w22.Y = 84;
        this.notebookMain.Add(this.fixed5);
        // Notebook tab
        this.labelSetup = new Gtk.Label();
        this.labelSetup.Name = "labelSetup";
        this.labelSetup.LabelProp = Mono.Unix.Catalog.GetString("Setup");
        this.notebookMain.SetTabLabel(this.fixed5, this.labelSetup);
        this.labelSetup.ShowAll();
        // Container child notebookMain.Gtk.Notebook+NotebookChild
        this.fixed7 = new Gtk.Fixed();
        this.fixed7.Name = "fixed7";
        this.fixed7.HasWindow = false;
        // Container child fixed7.Gtk.Fixed+FixedChild
        this.table2 = new Gtk.Table(((uint)(10)), ((uint)(4)), false);
        this.table2.Name = "table2";
        this.table2.RowSpacing = ((uint)(6));
        this.table2.ColumnSpacing = ((uint)(6));
        // Container child table2.Gtk.Table+TableChild
        this.buttonDrop = new Gtk.Button();
        this.buttonDrop.CanFocus = true;
        this.buttonDrop.Name = "buttonDrop";
        this.buttonDrop.UseUnderline = true;
        this.buttonDrop.Label = Mono.Unix.Catalog.GetString("Drop");
        this.table2.Add(this.buttonDrop);
        Gtk.Table.TableChild w24 = ((Gtk.Table.TableChild)(this.table2[this.buttonDrop]));
        w24.TopAttach = ((uint)(4));
        w24.BottomAttach = ((uint)(5));
        w24.XOptions = ((Gtk.AttachOptions)(4));
        w24.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table2.Gtk.Table+TableChild
        this.buttonLateJoin = new Gtk.Button();
        this.buttonLateJoin.Sensitive = false;
        this.buttonLateJoin.CanFocus = true;
        this.buttonLateJoin.Name = "buttonLateJoin";
        this.buttonLateJoin.UseUnderline = true;
        this.buttonLateJoin.Label = Mono.Unix.Catalog.GetString("Late Join");
        this.table2.Add(this.buttonLateJoin);
        Gtk.Table.TableChild w25 = ((Gtk.Table.TableChild)(this.table2[this.buttonLateJoin]));
        w25.TopAttach = ((uint)(6));
        w25.BottomAttach = ((uint)(7));
        w25.XOptions = ((Gtk.AttachOptions)(4));
        w25.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table2.Gtk.Table+TableChild
        this.hbox2 = new Gtk.HBox();
        this.hbox2.Name = "hbox2";
        this.hbox2.Spacing = 6;
        // Container child hbox2.Gtk.Box+BoxChild
        this.comboboxentryName = Gtk.ComboBoxEntry.NewText();
        this.comboboxentryName.AppendText(Mono.Unix.Catalog.GetString("Duckbob"));
        this.comboboxentryName.AppendText(Mono.Unix.Catalog.GetString("Raptor007"));
        this.comboboxentryName.AppendText(Mono.Unix.Catalog.GetString("ChubChub"));
        this.comboboxentryName.Name = "comboboxentryName";
        this.comboboxentryName.Active = 0;
        this.hbox2.Add(this.comboboxentryName);
        Gtk.Box.BoxChild w26 = ((Gtk.Box.BoxChild)(this.hbox2[this.comboboxentryName]));
        w26.Position = 0;
        w26.Expand = false;
        w26.Fill = false;
        // Container child hbox2.Gtk.Box+BoxChild
        this.buttonRename = new Gtk.Button();
        this.buttonRename.CanFocus = true;
        this.buttonRename.Name = "buttonRename";
        this.buttonRename.UseUnderline = true;
        this.buttonRename.Label = Mono.Unix.Catalog.GetString("Rename");
        this.hbox2.Add(this.buttonRename);
        Gtk.Box.BoxChild w27 = ((Gtk.Box.BoxChild)(this.hbox2[this.buttonRename]));
        w27.Position = 1;
        w27.Expand = false;
        w27.Fill = false;
        this.table2.Add(this.hbox2);
        Gtk.Table.TableChild w28 = ((Gtk.Table.TableChild)(this.table2[this.hbox2]));
        w28.TopAttach = ((uint)(5));
        w28.BottomAttach = ((uint)(6));
        w28.XOptions = ((Gtk.AttachOptions)(4));
        w28.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table2.Gtk.Table+TableChild
        this.label19 = new Gtk.Label();
        this.label19.Name = "label19";
        this.label19.LabelProp = Mono.Unix.Catalog.GetString("Team 1");
        this.table2.Add(this.label19);
        Gtk.Table.TableChild w29 = ((Gtk.Table.TableChild)(this.table2[this.label19]));
        w29.LeftAttach = ((uint)(1));
        w29.RightAttach = ((uint)(2));
        w29.XOptions = ((Gtk.AttachOptions)(4));
        w29.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table2.Gtk.Table+TableChild
        this.label20 = new Gtk.Label();
        this.label20.Name = "label20";
        this.label20.LabelProp = Mono.Unix.Catalog.GetString("Team 2");
        this.table2.Add(this.label20);
        Gtk.Table.TableChild w30 = ((Gtk.Table.TableChild)(this.table2[this.label20]));
        w30.LeftAttach = ((uint)(2));
        w30.RightAttach = ((uint)(3));
        w30.XOptions = ((Gtk.AttachOptions)(4));
        w30.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table2.Gtk.Table+TableChild
        this.label21 = new Gtk.Label();
        this.label21.Name = "label21";
        this.label21.LabelProp = Mono.Unix.Catalog.GetString("Team 3");
        this.table2.Add(this.label21);
        Gtk.Table.TableChild w31 = ((Gtk.Table.TableChild)(this.table2[this.label21]));
        w31.LeftAttach = ((uint)(3));
        w31.RightAttach = ((uint)(4));
        w31.XOptions = ((Gtk.AttachOptions)(4));
        w31.YOptions = ((Gtk.AttachOptions)(4));
        this.fixed7.Add(this.table2);
        Gtk.Fixed.FixedChild w32 = ((Gtk.Fixed.FixedChild)(this.fixed7[this.table2]));
        w32.X = 24;
        w32.Y = 31;
        // Container child fixed7.Gtk.Fixed+FixedChild
        this.labelCountdown = new Gtk.Label();
        this.labelCountdown.Name = "labelCountdown";
        this.labelCountdown.LabelProp = Mono.Unix.Catalog.GetString("Waiting2");
        this.fixed7.Add(this.labelCountdown);
        Gtk.Fixed.FixedChild w33 = ((Gtk.Fixed.FixedChild)(this.fixed7[this.labelCountdown]));
        w33.X = 357;
        w33.Y = 5;
        // Container child fixed7.Gtk.Fixed+FixedChild
        this.hbox1 = new Gtk.HBox();
        this.hbox1.Name = "hbox1";
        this.hbox1.Spacing = 6;
        // Container child hbox1.Gtk.Box+BoxChild
        this.buttonCancel = new Gtk.Button();
        this.buttonCancel.CanFocus = true;
        this.buttonCancel.Name = "buttonCancel";
        this.buttonCancel.UseUnderline = true;
        this.buttonCancel.Label = Mono.Unix.Catalog.GetString("Cancel");
        this.hbox1.Add(this.buttonCancel);
        Gtk.Box.BoxChild w34 = ((Gtk.Box.BoxChild)(this.hbox1[this.buttonCancel]));
        w34.Position = 0;
        w34.Expand = false;
        w34.Fill = false;
        // Container child hbox1.Gtk.Box+BoxChild
        this.buttonWait = new Gtk.Button();
        this.buttonWait.CanFocus = true;
        this.buttonWait.Name = "buttonWait";
        this.buttonWait.UseUnderline = true;
        this.buttonWait.Label = Mono.Unix.Catalog.GetString("Wait");
        this.hbox1.Add(this.buttonWait);
        Gtk.Box.BoxChild w35 = ((Gtk.Box.BoxChild)(this.hbox1[this.buttonWait]));
        w35.Position = 1;
        w35.Expand = false;
        w35.Fill = false;
        // Container child hbox1.Gtk.Box+BoxChild
        this.buttonStartGame = new Gtk.Button();
        this.buttonStartGame.CanFocus = true;
        this.buttonStartGame.Name = "buttonStartGame";
        this.buttonStartGame.UseUnderline = true;
        this.buttonStartGame.Label = Mono.Unix.Catalog.GetString("Start Game");
        this.hbox1.Add(this.buttonStartGame);
        Gtk.Box.BoxChild w36 = ((Gtk.Box.BoxChild)(this.hbox1[this.buttonStartGame]));
        w36.Position = 2;
        w36.Expand = false;
        w36.Fill = false;
        this.fixed7.Add(this.hbox1);
        Gtk.Fixed.FixedChild w37 = ((Gtk.Fixed.FixedChild)(this.fixed7[this.hbox1]));
        w37.X = 390;
        w37.Y = 333;
        this.notebookMain.Add(this.fixed7);
        Gtk.Notebook.NotebookChild w38 = ((Gtk.Notebook.NotebookChild)(this.notebookMain[this.fixed7]));
        w38.Position = 1;
        // Notebook tab
        this.labelJoin = new Gtk.Label();
        this.labelJoin.Sensitive = false;
        this.labelJoin.Name = "labelJoin";
        this.labelJoin.LabelProp = Mono.Unix.Catalog.GetString("Join");
        this.notebookMain.SetTabLabel(this.fixed7, this.labelJoin);
        this.labelJoin.ShowAll();
        this.Add(this.notebookMain);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 610;
        this.DefaultHeight = 523;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.comboboxentryArduinoPorts.Changed += new System.EventHandler(this.TransceiverChanged);
        this.comboboxentryArduinoPorts.EditingDone += new System.EventHandler(this.TransceiverChanged);
        this.buttonStartHost.Clicked += new System.EventHandler(this.StartGameType);
        this.buttonRename.Clicked += new System.EventHandler(this.RenamePlayer);
        this.buttonDrop.Clicked += new System.EventHandler(this.DropPlayer);
        this.buttonCancel.Clicked += new System.EventHandler(this.CancelGame);
        this.buttonWait.Clicked += new System.EventHandler(this.DelayGame);
    }
}
